# Important Pandas Library

Pandas is a Python library used for working with structured or tabular data.

In Machine Learning, Pandas is commonly used to load, inspect, clean, transform, and prepare datasets before training a model.

In [1]:
import numpy as np
import pandas as pd

## DataFrame

A **DataFrame** is a two-dimensional table used to store structured data.

- Rows = Samples / Observations
- Columns = Features / Variables

In Machine Learning, a DataFrame is commonly used to inspect, clean, transform, and prepare a dataset before training a model.

In [2]:
data = [
    ['Nissan', 'Stanza', None, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, 180, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Toyota', 'Corolla', 2018, 132, 4, 'AUTOMATIC', None, 19500],
    ['Honda', 'Civic', 2020, 158, 4, 'AUTOMATIC', 'sedan', 22000],
    ['Ford', 'Mustang', None, 310, 4, 'AUTOMATIC', 'coupe', 35500],
    ['Chevrolet', 'Malibu', 2016, 160, 4, 'AUTOMATIC', 'sedan', 23500],
    ['Mazda', 'MX-5', 2021, 181, 4, 'MANUAL', 'convertible', 27000],
    ['BMW', '3 Series', 2020, 255, 4, 'AUTOMATIC', 'sedan', 41000],
    ['Mercedes-Benz', 'C-Class', 2019, 255, 4, 'AUTOMATIC', 'sedan', None],
    ['Subaru', 'Impreza', 2018, 152, 4, 'MANUAL', 'hatchback', 21000]
]

columns = [
    'Make',
    'Model',
    'Year',
    'Engine HP',
    'Engine Cylinders',
    'Transmission Type',
    'Vehicle_Style',
    'MSRP'
]

# Create a DataFrame from the data and column names
df = pd.DataFrame(data, columns=columns)

df

            Make     Model    Year  ...  Transmission Type  Vehicle_Style     MSRP
0         Nissan    Stanza     NaN  ...             MANUAL          sedan   2000.0
1        Hyundai    Sonata  2017.0  ...          AUTOMATIC          Sedan  27150.0
2         Toyota   Corolla  2018.0  ...          AUTOMATIC           None  19500.0
3          Honda     Civic  2020.0  ...          AUTOMATIC          sedan  22000.0
4           Ford   Mustang     NaN  ...          AUTOMATIC          coupe  35500.0
5      Chevrolet    Malibu  2016.0  ...          AUTOMATIC          sedan  23500.0
6          Mazda      MX-5  2021.0  ...             MANUAL    convertible  27000.0
7            BMW  3 Series  2020.0  ...          AUTOMATIC          sedan  41000.0
8  Mercedes-Benz   C-Class  2019.0  ...          AUTOMATIC          sedan      NaN
9         Subaru   Impreza  2018.0  ...             MANUAL      hatchback  21000.0

[10 rows x 8 columns]

In [3]:
df.head(n=2)

      Make   Model    Year  ...  Transmission Type  Vehicle_Style     MSRP
0   Nissan  Stanza     NaN  ...             MANUAL          sedan   2000.0
1  Hyundai  Sonata  2017.0  ...          AUTOMATIC          Sedan  27150.0

[2 rows x 8 columns]

## Series

A **Series** is a one-dimensional data structure in Pandas and can usually be thought of as one column of a DataFrame.

In Machine Learning, a Series can represent a single Feature or a Target variable.

In [4]:
df['Engine HP']  # Select one column as a Series

0    138
1    180
2    132
3    158
4    310
5    160
6    181
7    255
8    255
9    152
Name: Engine HP, dtype: int64

In [5]:
df[['Make', 'Model', 'MSRP']]  # Select multiple columns

            Make     Model     MSRP
0         Nissan    Stanza   2000.0
1        Hyundai    Sonata  27150.0
2         Toyota   Corolla  19500.0
3          Honda     Civic  22000.0
4           Ford   Mustang  35500.0
5      Chevrolet    Malibu  23500.0
6          Mazda      MX-5  27000.0
7            BMW  3 Series  41000.0
8  Mercedes-Benz   C-Class      NaN
9         Subaru   Impreza  21000.0

Selecting multiple columns is commonly used when choosing Features that will later form a **Feature Matrix**.

In [6]:
df['id'] = range(1, len(df) + 1)  # Add an ID column based on the number of rows
df

            Make     Model    Year  ...  Vehicle_Style     MSRP  id
0         Nissan    Stanza     NaN  ...          sedan   2000.0   1
1        Hyundai    Sonata  2017.0  ...          Sedan  27150.0   2
2         Toyota   Corolla  2018.0  ...           None  19500.0   3
3          Honda     Civic  2020.0  ...          sedan  22000.0   4
4           Ford   Mustang     NaN  ...          coupe  35500.0   5
5      Chevrolet    Malibu  2016.0  ...          sedan  23500.0   6
6          Mazda      MX-5  2021.0  ...    convertible  27000.0   7
7            BMW  3 Series  2020.0  ...          sedan  41000.0   8
8  Mercedes-Benz   C-Class  2019.0  ...          sedan      NaN   9
9         Subaru   Impreza  2018.0  ...      hatchback  21000.0  10

[10 rows x 9 columns]

In [7]:
del df['id']  # Delete the ID column
df

            Make     Model    Year  ...  Transmission Type  Vehicle_Style     MSRP
0         Nissan    Stanza     NaN  ...             MANUAL          sedan   2000.0
1        Hyundai    Sonata  2017.0  ...          AUTOMATIC          Sedan  27150.0
2         Toyota   Corolla  2018.0  ...          AUTOMATIC           None  19500.0
3          Honda     Civic  2020.0  ...          AUTOMATIC          sedan  22000.0
4           Ford   Mustang     NaN  ...          AUTOMATIC          coupe  35500.0
5      Chevrolet    Malibu  2016.0  ...          AUTOMATIC          sedan  23500.0
6          Mazda      MX-5  2021.0  ...             MANUAL    convertible  27000.0
7            BMW  3 Series  2020.0  ...          AUTOMATIC          sedan  41000.0
8  Mercedes-Benz   C-Class  2019.0  ...          AUTOMATIC          sedan      NaN
9         Subaru   Impreza  2018.0  ...             MANUAL      hatchback  21000.0

[10 rows x 8 columns]

## Index

An **Index** identifies the rows of a DataFrame.

It helps us locate, select, and manage individual Samples or Observations in a dataset.

In [8]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [9]:
df.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df

            Make     Model    Year  ...  Transmission Type  Vehicle_Style     MSRP
a         Nissan    Stanza     NaN  ...             MANUAL          sedan   2000.0
b        Hyundai    Sonata  2017.0  ...          AUTOMATIC          Sedan  27150.0
c         Toyota   Corolla  2018.0  ...          AUTOMATIC           None  19500.0
d          Honda     Civic  2020.0  ...          AUTOMATIC          sedan  22000.0
e           Ford   Mustang     NaN  ...          AUTOMATIC          coupe  35500.0
f      Chevrolet    Malibu  2016.0  ...          AUTOMATIC          sedan  23500.0
g          Mazda      MX-5  2021.0  ...             MANUAL    convertible  27000.0
h            BMW  3 Series  2020.0  ...          AUTOMATIC          sedan  41000.0
i  Mercedes-Benz   C-Class  2019.0  ...          AUTOMATIC          sedan      NaN
j         Subaru   Impreza  2018.0  ...             MANUAL      hatchback  21000.0

[10 rows x 8 columns]

In [10]:
df.iloc[[1, 2, 4]]

      Make    Model    Year  ...  Transmission Type  Vehicle_Style     MSRP
b  Hyundai   Sonata  2017.0  ...          AUTOMATIC          Sedan  27150.0
c   Toyota  Corolla  2018.0  ...          AUTOMATIC           None  19500.0
e     Ford  Mustang     NaN  ...          AUTOMATIC          coupe  35500.0

[3 rows x 8 columns]

`iloc` means **Integer Location** and is used to select rows by their numerical position.

In [11]:
df = df.reset_index(drop=True)
df

            Make     Model    Year  ...  Transmission Type  Vehicle_Style     MSRP
0         Nissan    Stanza     NaN  ...             MANUAL          sedan   2000.0
1        Hyundai    Sonata  2017.0  ...          AUTOMATIC          Sedan  27150.0
2         Toyota   Corolla  2018.0  ...          AUTOMATIC           None  19500.0
3          Honda     Civic  2020.0  ...          AUTOMATIC          sedan  22000.0
4           Ford   Mustang     NaN  ...          AUTOMATIC          coupe  35500.0
5      Chevrolet    Malibu  2016.0  ...          AUTOMATIC          sedan  23500.0
6          Mazda      MX-5  2021.0  ...             MANUAL    convertible  27000.0
7            BMW  3 Series  2020.0  ...          AUTOMATIC          sedan  41000.0
8  Mercedes-Benz   C-Class  2019.0  ...          AUTOMATIC          sedan      NaN
9         Subaru   Impreza  2018.0  ...             MANUAL      hatchback  21000.0

[10 rows x 8 columns]

## Accessing Elements

Accessing elements means selecting specific Columns, Rows, or values from a DataFrame.

This is useful when exploring a dataset or selecting Features and Samples for further analysis.

In [12]:
df['MSRP']  # Select one Column

0     2000.0
1    27150.0
2    19500.0
3    22000.0
4    35500.0
5    23500.0
6    27000.0
7    41000.0
8        NaN
9    21000.0
Name: MSRP, dtype: float64

In [13]:
df[['Make', 'Model']]  # Select multiple Columns

            Make     Model
0         Nissan    Stanza
1        Hyundai    Sonata
2         Toyota   Corolla
3          Honda     Civic
4           Ford   Mustang
5      Chevrolet    Malibu
6          Mazda      MX-5
7            BMW  3 Series
8  Mercedes-Benz   C-Class
9         Subaru   Impreza

In [14]:
df.iloc[5]  # Select the sixth Row

Make                 Chevrolet
Model                   Malibu
Year                    2016.0
Engine HP                  160
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            sedan
MSRP                   23500.0
Name: 5, dtype: object

## Element-wise Operations

Element-wise operations apply the same operation to every value in a Series or Column.

In Machine Learning, these operations are useful for transforming Features, creating new Features, or applying conditions to data.

In [15]:
df['Engine HP'] * 2

0    276
1    360
2    264
3    316
4    620
5    320
6    362
7    510
8    510
9    304
Name: Engine HP, dtype: int64

In [16]:
df['Year'] >= 2015

0    False
1     True
2     True
3     True
4    False
5     True
6     True
7     True
8     True
9     True
Name: Year, dtype: bool

The comparison returns Boolean values:

- `True` = the condition is satisfied
- `False` = the condition is not satisfied

These Boolean values can later be used for Filtering.

## Filtering

Filtering is used to select only the Rows that satisfy a specific condition.

It is commonly used in Data Cleaning, Data Analysis, and creating subsets of a dataset.

In [17]:
df[df['Make'] == 'Nissan']

     Make   Model  Year  ...  Transmission Type  Vehicle_Style    MSRP
0  Nissan  Stanza   NaN  ...             MANUAL          sedan  2000.0

[1 rows x 8 columns]

In [18]:
df[
    (df['Make'] == 'Hyundai') &
    (df['Year'] >= 2015)
]

      Make   Model    Year  ...  Transmission Type  Vehicle_Style     MSRP
1  Hyundai  Sonata  2017.0  ...          AUTOMATIC          Sedan  27150.0

[1 rows x 8 columns]

When combining multiple conditions:

- `&` = AND
- `|` = OR

## String Operations

String Operations are used to clean and standardize text or Categorical Features.

This is important because values such as `Sedan`, `SEDAN`, and `sedan` may otherwise be treated as different categories.

In [19]:
'machine learning zoomcamp'.replace(' ', '_')

'machine_learning_zoomcamp'

In [20]:
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2           None
3          sedan
4          coupe
5          sedan
6    convertible
7          sedan
8          sedan
9      hatchback
Name: Vehicle_Style, dtype: object

In [21]:
df['Vehicle_Style'] = (
    df['Vehicle_Style']
    .str.replace(' ', '_')
    .str.lower()
)

df

            Make     Model    Year  ...  Transmission Type  Vehicle_Style     MSRP
0         Nissan    Stanza     NaN  ...             MANUAL          sedan   2000.0
1        Hyundai    Sonata  2017.0  ...          AUTOMATIC          sedan  27150.0
2         Toyota   Corolla  2018.0  ...          AUTOMATIC           None  19500.0
3          Honda     Civic  2020.0  ...          AUTOMATIC          sedan  22000.0
4           Ford   Mustang     NaN  ...          AUTOMATIC          coupe  35500.0
5      Chevrolet    Malibu  2016.0  ...          AUTOMATIC          sedan  23500.0
6          Mazda      MX-5  2021.0  ...             MANUAL    convertible  27000.0
7            BMW  3 Series  2020.0  ...          AUTOMATIC          sedan  41000.0
8  Mercedes-Benz   C-Class  2019.0  ...          AUTOMATIC          sedan      NaN
9         Subaru   Impreza  2018.0  ...             MANUAL      hatchback  21000.0

[10 rows x 8 columns]

- `.str.replace(' ', '_')` replaces spaces with underscores.
- `.str.lower()` converts text to lowercase.

Example:

`four door sedan` → `four_door_sedan`

## Summarizing Operations

Summarizing Operations help us understand the overall characteristics of a dataset.

They are an important part of **Data Understanding** and **Exploratory Data Analysis (EDA)** before training a Machine Learning model.

In [22]:
df.describe().round(3)  # Round the summary statistics to 3 decimal places

           Year  Engine HP  Engine Cylinders       MSRP
count     8.000     10.000              10.0      9.000
mean   2018.625    192.100               4.0  24294.444
std       1.685     60.021               0.0  10936.706
min    2016.000    132.000               4.0   2000.000
25%    2017.750    153.500               4.0  21000.000
50%    2018.500    170.000               4.0  23500.000
75%    2020.000    236.500               4.0  27150.000
max    2021.000    310.000               4.0  41000.000

`describe()` calculates summary statistics for Numerical Columns, such as:

- count
- mean
- standard deviation
- minimum
- quartiles
- maximum

These statistics help us understand the Scale, Distribution, and possible unusual values in Features.

In [23]:
df.nunique()

Make                 10
Model                10
Year                  6
Engine HP             9
Engine Cylinders      1
Transmission Type     2
Vehicle_Style         4
MSRP                  9
dtype: int64

`nunique()` counts the number of unique values in each Column.

It is especially useful for understanding Categorical Features and checking how many Categories are present.

## Missing Values

Missing Values are data points that are unavailable or not recorded.

In this dataset, `None` is used to represent missing information.

Checking Missing Values is important because many Machine Learning algorithms cannot work with missing data directly and may require the values to be handled before training.

In [24]:
df.isnull()

    Make  Model   Year  ...  Transmission Type  Vehicle_Style   MSRP
0  False  False   True  ...              False          False  False
1  False  False  False  ...              False          False  False
2  False  False  False  ...              False           True  False
3  False  False  False  ...              False          False  False
4  False  False   True  ...              False          False  False
5  False  False  False  ...              False          False  False
6  False  False  False  ...              False          False  False
7  False  False  False  ...              False          False  False
8  False  False  False  ...              False          False   True
9  False  False  False  ...              False          False  False

[10 rows x 8 columns]

`isnull()` checks every value in the DataFrame and returns:

- `True` = Missing Value
- `False` = Value is available

In [25]:
df.isnull().sum()

Make                 0
Model                0
Year                 2
Engine HP            0
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        1
MSRP                 1
dtype: int64

`isnull().sum()` counts the number of Missing Values in each Column.

This helps identify which Features contain missing data and may require Data Cleaning before training a model.

In [26]:
df.isnull().mean() * 100

Make                  0.0
Model                 0.0
Year                 20.0
Engine HP             0.0
Engine Cylinders      0.0
Transmission Type     0.0
Vehicle_Style        10.0
MSRP                 10.0
dtype: float64

`isnull().mean() * 100` calculates the percentage of Missing Values in each Column.

## Grouping

Grouping divides a dataset into Categories and then calculates a summary for each group.

It helps us explore Patterns and differences between groups within the dataset.

In [27]:
df.groupby('Transmission Type').MSRP.max()

Transmission Type
AUTOMATIC    41000.0
MANUAL       27000.0
Name: MSRP, dtype: float64

This groups the data by `Transmission Type` and calculates the maximum `MSRP` for each group.

Grouping is useful when exploring the relationship between a Categorical Feature and a Numerical Feature.

## Getting NumPy Arrays

Pandas is useful for preparing and managing datasets, while many Machine Learning algorithms work internally with NumPy Arrays or Matrices.

Therefore, Pandas data can be converted into NumPy format when needed.

In [28]:
df.MSRP.values

array([ 2000., 27150., 19500., 22000., 35500., 23500., 27000., 41000.,
          nan, 21000.])

In [29]:
df['MSRP'].to_numpy()

array([ 2000., 27150., 19500., 22000., 35500., 23500., 27000., 41000.,
          nan, 21000.])

`to_numpy()` converts a Pandas Series into a NumPy Array.

For example, a Target Column can later be converted into the Target Vector `y`.

In [30]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': nan,
  'Engine HP': 138,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000.0},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017.0,
  'Engine HP': 180,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150.0},
 {'Make': 'Toyota',
  'Model': 'Corolla',
  'Year': 2018.0,
  'Engine HP': 132,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': None,
  'MSRP': 19500.0},
 {'Make': 'Honda',
  'Model': 'Civic',
  'Year': 2020.0,
  'Engine HP': 158,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 22000.0},
 {'Make': 'Ford',
  'Model': 'Mustang',
  'Year': nan,
  'Engine HP': 310,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'coupe',
  'MSRP': 35500.0},
 {'Make': 'Chevrolet',
  'Model': 'Malibu',
  'Year': 2016.0,
  'Engine HP': 160,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 23500.0},
 {'Make': 'Mazda',
  'Model': 'MX-5',
  'Year': 2021.0,
  'Engine HP': 181,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 27000.0},
 {'Make': 'BMW',
  'Model': '3 Series',
  'Year': 2020.0,
  'Engine HP': 255,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 41000.0},
 {'Make': 'Mercedes-Benz',
  'Model': 'C-Class',
  'Year': 2019.0,
  'Engine HP': 255,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': nan},
 {'Make': 'Subaru',
  'Model': 'Impreza',
  'Year': 2018.0,
  'Engine HP': 152,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'hatchback',
  'MSRP': 21000.0}]

`to_dict(orient='records')` converts a DataFrame into a List of Dictionaries.

Each Dictionary represents one Row or Record.

This format is useful when transferring data to other Python code, APIs, or application systems.